### ISSUE TITLE
Installing The Mod

### ISSUE THREAD

**Issue by Zekrodiak** [LethalMods/LethalExpansionCore#11]
hi, this isn't an issue but didn't know where to comment so I just wanted to ask...do I replace the lethal expansion mod files with yours or do it put your mods (LE, SDK, LE Core) in a separate folder?

**Comment by 21Joakim** [comment]
Preferably in a separate directory, you do not need to have both LE and LECore installed at the same time, LECore works without LE. Note if you put modules inside the LE directory they will automatically be ignored unless the `LoadDefaultBundles` config option is set to `true`
