### ISSUE TITLE
Noisemaker not working properly

### ISSUE THREAD

**Issue by Wesley-wasnietavailabledusdanmaarzo** [LethalMods/LethalExpansionCore#15]
Will this be updated to the latest version of LE?
There are some quite important fixes which seem to be still be an issue here.

**Comment by 21Joakim** [comment]
Any issue in particular you're referring to?

**Comment by Wesley-wasnietavailabledusdanmaarzo** [comment]
One that is mainly a problem atm is that custom noisemakers pitch don't align with the settings if that makes sense

**Comment by 21Joakim** [comment]
That should be fixed in the latest version 1.3.15 (https://github.com/LethalMods/LethalExpansionCore/pull/13)

**Comment by Wesley-wasnietavailabledusdanmaarzo** [comment]
Awesome
