### ISSUE TITLE
help with some original LE features

### ISSUE THREAD

**Issue by HamedAlmanthari** [LethalMods/LethalExpansionCore#6]
hi. i really like this debloated version of LE but i also liked some HUD features from the original LE. the 3 config options ShowMoonPriceInCatalogue, ShowMoonRankInCatalogue, ShowMoonWeatherInCatalogue especially i couldn't find another mod for them instead. is there a way to use just these 3 options with LECore?

**Comment by HamedAlmanthari** [comment]
also this is not a bug, sorry

**Comment by 21Joakim** [comment]
The purpose of LECore is to remove **everything** which is not necessary for LethalSDK, the API that is used for other mods to add scrap and moons. Simply put there will not be any features like that in LECore

**Comment by HamedAlmanthari** [comment]
do you know of a mod that does these things?
