### ISSUE TITLE
Can't load custom moons

### ISSUE THREAD

**Issue by Entity378** [LethalMods/LethalExpansionCore#7]
after selecting the custom moon from the terminal and pulling the lever to land on the moon the game softlocks giving this error
![bug](https://github.com/LethalMods/LethalExpansionCore/assets/150670165/9959e547-6576-4a49-aa8e-b69568cec666)

**Comment by AudioKnight** [comment]
Seconding this issue. The softlock goes away if both LethalExpansion and LethalExpansionCore are loaded together with "UseOriginalLethalExpansion" set to true.

**Comment by 21Joakim** [comment]
Which moon and could you provide the log file?

**Comment by AudioKnight** [comment]
It's my custom moon Auralis from my Starlancer mod. I'm away from my computer for a bit, but if I have time I'll reproduce the error later and post the log. It looked pretty similar to OP's iirc.

**Comment by 21Joakim** [comment]
Also, are you using the latest version (`1.3.12`) and if you are could you test with `1.3.10` as well?

**Comment by AudioKnight** [comment]
Will do!

**Comment by ZigzagAwaka** [comment]
Excuse me but I don't know where to find the "UseOriginalLethalExpansion" setting since it dosn't appear in configs, can someone help me?
